
####################################
#    Services Configuration File   #
#    Change the service and name!  #
####################################
[services]
serviceNames = ["Plex", "Samba"]
systemdID = ["plexmediaserver", "smbd"]
aptitudeID = ["plexmediaserver","samba"]